import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { MyLink } from "@/components/my-link";
import { headers } from "next/headers";
import { Back } from "./back";
import classNames from "classnames";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className={classNames(
            "p-5 w-[640px] min-h-[500px]",
            "mx-auto mt-[50%] translate-y-[-50%]",
            "bg-gray-100 shadow-2xl rounded-2xl",
          )}
        >
          <Back />
          {children}
        </div>
      </body>
    </html>
  );
}
